title: Jack Ford

collections:
  projects:
    output: true
  writeups:
    output: true
  personal:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "projects"
  - scope:
      path: ""
      type: "writeups"
    values:
      layout: "writeups"
  - scope:
      path: ""
      type: "personal"
    values:
      layout: "personal"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
