title: Jack Ford

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

collections:
  projects:
    output: true
  writeups:
    output: true
  personal:
    output: true
  flags:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "projects"
  - scope:
      path: ""
      type: "writeups"
    values:
      layout: "writeups"
  - scope:
      path: ""
      type: "personal"
    values:
      layout: "personal"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

obsidian:
  enable_wikilinks: true
  process_collections: ["writeups"]
  vault_dir: "."
  strict: false

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-obsidian

exclude:
  - README.md
